language: scala
scala:
  - 2.10.6
  - 2.11.8
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom
  
notifications:
  email: false
